In [ ]:
#Neuron
import numpy as np

x=[1,2,3]
w=[4,5,6]
  
outputs=np.dot(x,w)

print(outputs)

32


In [11]:
#Layer


w=np.array([[1,3,4],[4,5,6],[7,8,9]])
b=np.array([1,2,3])
x=np.array([3.4,5.6,7.8]).T



print(w.shape)
print(b.shape)
print(x.shape)

(3, 3)
(3,)
(3,)


In [12]:
output.shape

(3,)

BATCH

In [19]:
x=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,10]])
w=np.array([[1,2,3,4],[4,5,6,7],[6,7,8,9]])

b=np.array([[1,1,1],[2,2,3],[3,3,3]])

In [20]:
x

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [22]:
print(x.shape)
print(x.ndim)

(3, 4)
2


In [23]:
w

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [24]:
print(w.shape)
print(w.ndim)

(3, 4)
2


In [25]:
b

array([[1, 1, 1],
       [2, 2, 3],
       [3, 3, 3]])

In [26]:
print(b.shape)
print(b.ndim)

(3, 3)
2


In [31]:
batch_result=np.dot(x,w.T)+b

In [ ]:
print(batch_result.shape)
print(batch_result.ndim)